### ISSUE TITLE
[troubleshooting] http_proxy not working

### ISSUE THREAD

**Issue by pahud** [pahud/kops-bjs#11]
There are some cases the proxy is not working. This article will walk you through the debugging.

## how to make sure the proxy is working

- ssh into the master node and type
`set | gre http_proxy` and you should see `http_proxy`, `https_proxy` and `no_proxy1` env variables.
- run `curl -v -L -x $http_proxy https://fb.com` you should be able to follow some http redirections and see HTTP 200 OK. If you fail or get `HTTP/1.1 503`, your http_proxy could not be working.

## check your Fargate

- go to `Amazon ECS` console from the region you launch your `gost` service and you should be able to see a task in `RUNNING` state like this:

![image](https://user-images.githubusercontent.com/278432/40874006-8855754c-669c-11e8-98a6-c4e13d7bfd7b.png)

- click `Stopped` tab in the button and you should see empty `Stopped` tasks

![image](https://user-images.githubusercontent.com/278432/40874016-acb3657a-669c-11e8-8309-55ff6ecf2d5f.png)

If you see some stopped tasks, chances are your Fargate task can't become stable. I've seen some case like this but at this moment you have to manually run the `gost` service either with Amazon ECS with EC2 instances or manually `docker run` on the EC2 instance. (HOWTO TBD)

## check your ELB 
check your ELB target group in the region where you launch the `gost` service. You should see a target group named `gost-gost-service` and there's a `Registered target` and the status should be `healthy`. If not, chances are the Fargate Task is not stable. You will need to run the `gost` service with Amazon ECS with Linux EC2 or `docker run` manually.(HOWTO TBD) 
![image](https://user-images.githubusercontent.com/278432/40874067-3c1138f0-669d-11e8-9f5e-e56fc8ed9607.png)

**Comment by brant4test** [comment]
Very helpful!

1. checked, 
```
1/3 masters have http_proxy, https_proxy and no_proxy
2/3 masters have http_proxy, https_proxy 
3/3 curl -v -L -x $http_proxy ... works.
```
2. checked,
```
Under Service : gost, one Running task
```
3. checked,
```
Under Target group: gost-gost-service, there's a healthy below Registered targets
```
