### ISSUE TITLE
kube-dns issue on kops 1.9.1

### ISSUE THREAD

**Issue by MMichael-S** [pahud/kops-bjs#14]
After upgrade kops from 1.9.0 to 1.9.1,  when create cluster, pod(kube-dns) can't work normally and show "ContainerCreating" status for long time.

BTW, I found some comments about kube-dns on kops 1.9.1 release.
https://github.com/kubernetes/kops/releases/tag/1.9.1

[kops1.9.1 kube-dns issue.pdf](https://github.com/pahud/kops-bjs/files/2091133/kops1.9.1.kube-dns.issue.pdf)

**Comment by pahud** [comment]
I am closing this stale issue. Please reopen it if it still exists in the latest 1.9.1.
