### ISSUE TITLE
Proposal of accelerating Istio and Quay.io on AWS China

### ISSUE THREAD

**Issue by brant4test** [pahud/kops-bjs#20]
Super excited to have accelerated experience using Kops on AWS China. Appreciate making it happen.

Can I have a proposal of accelerating Istio and Quay.io on AWS China as well? As Istio and service mesh are getting more and more popular worldwide. Thanks!

from LinSun: Catch up on the Istio and service mesh excitement from Kubecon 2017! 
https://developer.ibm.com/dwblog/2017/istio-service-mesh-kubecon-news-announcements/

And loads of Service mesh sessions in KubeCon + CloudNativeCon Europe 2018
https://kccnceu18.sched.com/overview/type/Service+mesh

**Comment by pahud** [comment]
The Charts of Istio contains some imaeg from `quay.io` 

for example, the image of `prometheus` is defined in `quay.io`
https://github.com/kubernetes/charts/blob/master/incubator/istio/values.yaml#L228

It is not possible at this moment for docker daemon to pull images from different registry mirrors. For now we only have `registry.docker-cn.com` as docker hub registry mirror and we can do nothing for images from `quay.io` and `gcr.io` if they were hardcoded in the helm charts or other artifacts files.

I noticed moby may be working on this(https://github.com/moby/moby/pull/34319) and hopefully maybe one day we can build our private registry mirror in our own AWS VPC to accelerate image downloads from `docker.io`, `gcr.io` and `quay.io` without hacking the original helm charts. That would be a better way to go with minimal maintainence effort.

**Comment by brant4test** [comment]
Thanks a lot! Pahud
