### ISSUE TITLE
How to deploy k8s into private subnet

### ISSUE THREAD

**Issue by alyanli** [pahud/kops-bjs#23]
For the production environment, we can't deploy k8s into public subnet. On the contrary, private subnet is a must. here is a some tips to help you achieve this goal

1. VPC  in zhy region
10.2.0.0/16
 cn-northwest-1a  cn-northwest-1b  cn-northwest-1c
10.2.10.0              10.2.20.0              10.2.30.0                    Public   Subnet
10.2.40.0              10.2.50.0              10.2.60.0                    Private  Subnet
have nat gw setup in public subnet and rbs in private subnet
2. here is a sample yaml to deploy 3 master and 3 node into private subnet

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-08-06T10:54:18Z
  name: kopsdemo.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Owner: Martin Yang
    Team: Dev
  cloudProvider: aws
  configBase: s3://kops-demo-store/kopsdemo.k8s.local
  docker:
    logDriver: ""
    registryMirrors:
    - https://registry.docker-cn.com
  egressProxy:
    excludes: amazonaws.com.cn,amazonaws.cn,aliyun.cn,aliyuncs.com,registry.docker-cn.com,127.0.0.1,localhost,api.kopsdemo.k8s.local,kopsdemo.k8s.local,100.64.0.1,100.64.0.0/10,169.254.169.254,10.2.0.0/16,s3.cn-north-1.amazonaws.com.cn
    httpProxy:
      host: internal-ProxyELB-kops-proxy-2010081744.cn-northwest-1.elb.amazonaws.com.cn
      port: 8888
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-cn-northwest-1a
      name: a
    - instanceGroup: master-cn-northwest-1b
      name: b
    - instanceGroup: master-cn-northwest-1c
      name: c
    image: anjia0532/etcd:2.2.1
    name: main
  - etcdMembers:
    - instanceGroup: master-cn-northwest-1a
      name: a
    - instanceGroup: master-cn-northwest-1b
      name: b
    - instanceGroup: master-cn-northwest-1c
      name: c
    image: anjia0532/etcd:2.2.1
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    image: anjia0532/kube-apiserver:v1.9.8
  kubeControllerManager:
    image: anjia0532/kube-controller-manager:v1.9.8
  kubeProxy:
    image: anjia0532/kube-proxy:v1.9.8
  kubeScheduler:
    image: anjia0532/kube-scheduler:v1.9.8
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.8
  masterInternalName: api.internal.kopsdemo.k8s.local
  masterPublicName: api.kopsdemo.k8s.local
  networkCIDR: 10.2.0.0/16
  networkID: vpc-7d4ef914
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: martin-nx
  subnets:
  - cidr: 10.2.40.0/24
    id: subnet-5244ec3b
    name: cn-northwest-1a
    type: Private
    zone: cn-northwest-1a
  - cidr: 10.2.50.0/24
    id: subnet-f7ab668c
    name: cn-northwest-1b
    type: Private
    zone: cn-northwest-1b
  - cidr: 10.2.60.0/24
    id: subnet-7f644d35
    name: cn-northwest-1c
    type: Private
    zone: cn-northwest-1c
  - cidr: 10.2.10.0/24
    id: subnet-a542eacc
    name: utility-cn-northwest-1a
    type: Utility
    zone: cn-northwest-1a
  - cidr: 10.2.20.0/24
    id: subnet-39ab6642
    name: utility-cn-northwest-1b
    type: Utility
    zone: cn-northwest-1b
  - cidr: 10.2.30.0/24
    id: subnet-e9654ca3
    name: utility-cn-northwest-1c
    type: Utility
    zone: cn-northwest-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

**Comment by alyanli** [comment]
please check the attached file for correct format
[kopsnew.txt](https://github.com/pahud/kops-bjs/files/2270485/kopsnew.txt)

**Comment by pahud** [comment]
Thanks for the sharing. I will update the `README` and create a reference link to this issue.

**Comment by pahud** [comment]
Thanks for your contribution. Will label this as a FAQ note.
