### ISSUE TITLE
Deploy cluster into existing subnets

### ISSUE THREAD

**Issue by jansony1** [pahud/kops-bjs#26]
#### Customer need to deploy their cluster into existing subnets, while Kops official page is not clear, as you could see here 
https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md#shared-subnets

Specifically for those parts,
```
export SUBNET_ID=subnet-12345678 # replace with your subnet id
export SUBNET_CIDR=10.100.0.0/24 # replace with your subnet CIDR
export SUBNET_IDS=$SUBNET_IDS # replace with your comma separated subnet ids

```

What you really need  is to just modify the script like below according to your subnet and zones, and keep other scripts no change in create_cluster_localmirror.sh  (PS: Only include necessary parts, )

```
kops create cluster \
     --zones=cn-north-1a,cn-north-1b \  
     --subnets=subnet-0d61600a9398604f5,subnet-00f5ce7457eec5f4b \
```

One thing to remember is that your zone's order shoule be **same** with subnet's order

**Comment by pahud** [comment]
@jansony1  Thanks for the sharing!
