### ISSUE TITLE
can't ssh into the master/instance nodes even specify --ssh-public-key

### ISSUE THREAD

**Issue by pahud** [pahud/kops-bjs#8]
In some cases, it may be desirable to use an existing AWS SSH key instead of allowing kops to create a new one. Providing the name of a key already in AWS is an alternative to `--ssh-public-key`.

```
spec:
  sshKeyName: myexistingkey
```

https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#sshkeyname

**Comment by MMichael-S** [comment]
👍
